clusterGroup:
  name: basic
  isHubCluster: false

  namespaces:
  - myNamespace

  subscriptions: {}

  projects:
  - myProject

  applications:
    gateway:
      name:
      namespace:
      project:
      path: charts/

    myApp:
      name: hello-world
      namespace: myNamespace
      project: myProject
      path: charts/hello-world
